Fs=4000;channels=1; bits=16;
r=audiorecorder(Fs,bits,channels);
duration=17;disp('Recording started');
recordblocking(r,duration);
disp('Recording Stopped');
X=getaudiodata(r);
%sound(X,Fs,bits);
t=0:1/Fs:(length(X)-1)/Fs;
subplot(2,1,1);plot(t,X,'linewidth',1.5);
xlabel('time (s)');ylabel('amplitude');
title('time domain plot of recording signal');
n=length(X);f=0:(n-1)*Fs/n;
y=fft(X,n);
F_0=(-n/2:n/2-1) *(Fs/n);
Y_0=fftshift(y);
AY_0=abs(Y_0);
subplot(2,1,2);plot(F_0,AY_0,'linewidth',1.5);
xlabel("frequency (HZ)");ylabel('amplitude');
title('frequency domain plot of recording signal');
filename="myvoice.wav";
audiowrite(filename,X,Fs);